### ISSUE TITLE
expose glutin::ModifiersState to KeyboardInput

### ISSUE THREAD

**Issue by bytebuddha** [christolliday/limn#18]
Would something simple like KeyboardInput(pub ElementState, pub ScanCode, pub Option<VirtualKeyCode>, pub ModifiersState) work?

**Comment by christolliday** [comment]
yes I think just adding ModifiersState to that struct would work, alternatively it could be changed to just pass the glutin/winit struct directly instead of destructuring.

**Comment by bytebuddha** [comment]
Yes i like that idea of just using glutin::WindowEvent better myself too. I'll submit a PR for it when i get the chance
