### ISSUE TITLE
External event source

### ISSUE THREAD

**Issue by bytebuddha** [christolliday/limn#25]
In my application i need to be able to read events from a std::process::ChildStdout. I have accomplished this for my use case by modifying the source of App, but i feel like there should be an easier way to do this than having to maintain a copy of the source. Maybe a function like `pub fn external(&mut self, func: FnMut(&mut Ui))` could be added to App, that runs once every frame. But i'm not sure what the actual signature would be.

**Comment by christolliday** [comment]
I think what you are describing can be achieved using a second thread to read from `std::process::ChildStdout` and then sending events to the main thread using `event_global`, this is how the clock example sends clock ticks.

You can add event handlers that run every frame by listening for the `FrameEvent` that was recently added but I'm not sure if that solves your problem.

**Comment by bytebuddha** [comment]
Ok looking into FrameEvent it appears to be just what i need, Thank you!
