### ISSUE TITLE
Use font-loader for loading fonts

### ISSUE THREAD

**Issue by jrmuizel** [christolliday/limn#4]
It's not very sophisticated but it works on all platforms and is better than having to include fonts in assets. It's what we use for font-loading in webrender/wrench.

**Comment by myfreeweb** [comment]
It uses fontconfig, which seems plenty sophisticated to me :D

**Comment by christolliday** [comment]
Yeah thanks for the heads up, wasn't aware of this library but ultimately this functionality will be needed, and it would be nice to have it as a dependency.

@MSleepyPanda I'm wondering though, does it support Android/iOS or is it planned to? It will probably be a while before limn is usable on those platforms but I still want to keep them in mind and minimize changes that will make it harder to support them.

**Comment by MSleepyPanda** [comment]
It should make sense to support those two targets as well, but we currently don't. Opened issues for both!

**Comment by christolliday** [comment]
Thanks! I should mention that adding support for those to font-loader shouldn't be a pre-requisite for adding font-loader support to limn. If anybody is interested in working on it, PRs are welcome!
If no one gets around to working on it I'll add it eventually, but it's not high priority for me yet.

**Comment by fschutt** [comment]
Also, please don't do this for images, either. `limn` should not be responsible for loading the data of images and loading fonts. These could, for example come over the network (ex. an FTP program that views data from a remote server). This is up to the user of the binary - `limn` should only have a `R: std::io::Read` trait bound and that's it.

**Comment by christolliday** [comment]
font-loader support added by #39
