### ISSUE TITLE
style! macro doesn't play nice with formatting

### ISSUE THREAD

**Issue by RoelofSol** [christolliday/limn#52]
Currently the style macro is defined to be 

`( $style_type:ident { $( $field:ident: $value:expr , )* } ) => {`

This is inconsistent with expected behaviour. My auto formatting was generated invalid code because it removed trailing comma's. 

So i suggest either 

- No trailing comma `( $style_type:ident { $( $field:ident: $value:expr ) , * } ) => {` ( https://github.com/christolliday/limn/pull/54)
 
- optional trailing comma `( $style_type:ident { $( $field:ident: $value:expr ) , * $(,)* } ) => {` ( https://github.com/christolliday/limn/pull/53 )

**Comment by christolliday** [comment]
fixed by #54
